server:
  internalPort: 8000
  externalPort: 8000
  runMode: debug
  domain: localhost
  name: shikposh-backend
  lang: fa
  WriteTimeout: 10s
  ReadTimeout: 10s
logger:
  filePath: ../logs/
  encoding: json
  level: debug
  logger: zerolog
cors:
  allowOrigins: "http://localhost:3000"
postgres:
  host: localhost
  port: 5432
  user: ali
  password: "pg123"
  dbName: "shikposh"
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  dialTimeout: 5s
  readTimeout: 5s
  writeTimeout: 5s
  poolSize: 10
  poolTimeout: 15s
  idleCheckFrequency: 500ms
elasticsearch:
  host: localhost
  port: 9200
  username: elastic
  password: "@aA123456"
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  accessTokenExpireDuration: 1440m # 24 hours
  refreshTokenExpireDuration: 720h # 30 days
jaeger:
  enabled: true
  otlpEndpoint: "http://localhost:4318"
  serviceName: shikposh-backend
  environment: development
  samplingRate: 1.0
