-- migrate:up
-- product_images (عکس‌ها بر اساس رنگ)
CREATE TABLE product_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_id BIGINT NOT NULL REFERENCES colors(id) ON DELETE CASCADE,
    url VARCHAR(500) NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_product_images_product ON product_images(product_id);
CREATE INDEX idx_product_images_color ON product_images(color_id);
CREATE INDEX idx_product_images_sort ON product_images(product_id, color_id, sort_order);

-- migrate:down
DROP INDEX IF EXISTS idx_product_images_sort;
DROP INDEX IF EXISTS idx_product_images_color;
DROP INDEX IF EXISTS idx_product_images_product;
DROP TABLE IF EXISTS product_images;

