-- migrate:up
-- Create colors table
CREATE TABLE IF NOT EXISTS colors (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    hex VARCHAR(7) NOT NULL, -- Hex color code (e.g., "#FF0000")
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_colors_deleted_at ON colors(deleted_at);
CREATE INDEX IF NOT EXISTS idx_colors_slug ON colors(slug);
CREATE UNIQUE INDEX IF NOT EXISTS idx_colors_name_unique ON colors(name) WHERE deleted_at IS NULL;

-- Create product_colors junction table for many-to-many relationship
CREATE TABLE IF NOT EXISTS product_colors (
    product_id BIGINT NOT NULL,
    color_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (product_id, color_id),
    CONSTRAINT fk_product_colors_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_product_colors_color FOREIGN KEY (color_id) REFERENCES colors(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_product_colors_product_id ON product_colors(product_id);
CREATE INDEX IF NOT EXISTS idx_product_colors_color_id ON product_colors(color_id);

-- migrate:down
DROP INDEX IF EXISTS idx_product_colors_color_id;
DROP INDEX IF EXISTS idx_product_colors_product_id;
DROP TABLE IF EXISTS product_colors;
DROP INDEX IF EXISTS idx_colors_name_unique;
DROP INDEX IF EXISTS idx_colors_slug;
DROP INDEX IF EXISTS idx_colors_deleted_at;
DROP TABLE IF EXISTS colors;

