-- migrate:up
-- product_variants (ترکیب رنگ + سایز با موجودی)
CREATE TABLE product_variants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_id BIGINT NOT NULL REFERENCES colors(id) ON DELETE CASCADE,
    size_id BIGINT NOT NULL REFERENCES sizes(id) ON DELETE CASCADE,
    stock INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (product_id, color_id, size_id)
);
CREATE INDEX idx_product_variants_product ON product_variants(product_id);
CREATE INDEX idx_product_variants_color ON product_variants(color_id);
CREATE INDEX idx_product_variants_size ON product_variants(size_id);

-- migrate:down
DROP INDEX IF EXISTS idx_product_variants_size;
DROP INDEX IF EXISTS idx_product_variants_color;
DROP INDEX IF EXISTS idx_product_variants_product;
DROP TABLE IF EXISTS product_variants;

